# Generated by Django 5.0.6 on 2024-06-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0002_perfilvisitante_nome_completo'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='perfil_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil_visitante.perfilvisitante'),
        ),
    ]
