# Generated by Django 5.0.6 on 2024-07-10 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_visitanteperguntaresposta_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto_pergunta',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
