# Generated by Django 5.0.6 on 2024-07-11 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_pergunta_texto_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteperguntaresposta',
            name='criado_em',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
