# Generated by Django 5.0.6 on 2024-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_visita', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10')])),
                ('gostou_visita', models.CharField(max_length=100)),
                ('idade', models.CharField(choices=[('5-7', '5, 6 ou 7 anos'), ('7-9', '7, 8 ou 9 anos'), ('10-12', '10, 11 ou 12 anos'), ('mais_de_12', 'Tenho mais que 12 anos')], max_length=20)),
                ('turma', models.CharField(choices=[('1', '1º ano do Fundamental'), ('2', '2º ano do Fundamental'), ('3', '3º ano do Fundamental'), ('4', '4º ano do Fundamental'), ('5', '5º ano do Fundamental')], max_length=50)),
                ('municipio_escola', models.CharField(choices=[('Itaparica', 'Itaparica'), ('Vera Cruz', 'Vera Cruz'), ('Outro', 'Outro')], max_length=50)),
            ],
        ),
    ]
