# Generated by Django 5.0.6 on 2024-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisitante',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
