# Generated by Django 5.0.6 on 2024-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0002_perfilvisitante_nome_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilvisitante',
            options={'ordering': ['nome_completo']},
        ),
    ]
