# Generated by Django 5.0.6 on 2024-07-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0003_alter_perfilvisitante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvisitante',
            name='gostou_visita',
            field=models.CharField(choices=[('Itaparica', 'Itaparica'), ('Vera Cruz', 'Vera Cruz'), ('Outro', 'Outro')], max_length=100),
        ),
    ]
