# Generated by Django 5.0.6 on 2024-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0004_alter_perfilvisitante_gostou_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvisitante',
            name='gostou_visita',
            field=models.CharField(choices=[('1', 'SIM'), ('0', 'NÃO')], max_length=100),
        ),
    ]
