# Generated by Django 5.0.6 on 2024-07-04 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0006_perfilvisitante_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilvisitante',
            name='criado_em',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
