# Generated by Django 5.0.6 on 2024-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_visitante', '0008_alter_perfilvisitante_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilvisitante',
            name='criado_em',
            field=models.DateTimeField(verbose_name='Data do cadastro'),
        ),
    ]
